version: '3.8'

services:
  db:
    image: mysql:8.2.0
    container_name: backend-ujian-spring-boot-java-db

    ports:
      - 3308:3306

    environment:
      MYSQL_ROOT_PASSWORD: 'toor'
      MYSQL_DATABASE: 'ujian-db'
      MYSQL_USER: 'spring'
      MYSQL_PASSWORD: 'boot'

    volumes:
      - mysqldata:/var/lib/mysql

    networks:
      - ujian-spring-boot-java-net

  pma:
    image: phpmyadmin:latest
    container_name: backend-ujian-spring-boot-java-pma
    depends_on:
      - db
    environment:
      PMA_HOST: db
    ports:
      - 8008:80
    networks:
      - ujian-spring-boot-java-net

# Volumes
volumes:
  mysqldata:
    driver: local

# Networks
networks:
  ujian-spring-boot-java-net:
    driver: bridge